In [1]:
import sys
sys.path.insert(0, '../')
from nn_cno import ode
import numpy as np
import itertools
import jax.numpy as jnp
import jax
import diffrax
import optax


In [10]:
c = ode.logicODE("../nn_cno/datasets/working_case_study/PKN-test.sif",
    "../nn_cno/datasets/working_case_study/MD-test.csv")
c.preprocessing()

In [3]:
sim  = c.simulate()

In [7]:
params = jnp.array(list(c.get_ODEparameters().values()))

In [11]:
%%timeit -n 1 -r 1
c.loss_function(params)

3.33 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [12]:
%%timeit 
c.loss_function(params)

189 µs ± 1.94 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
%%timeit -n 1 -r 1
c.loss_function_grad(params)

1min 1s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [15]:
%%timeit
c.loss_function_grad(params)

7.8 ms ± 88.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
c.fit(max_iter=1000  )

step 0, loss: 0.1511961966753006
	params: [1.0099999  2.01       0.09000007 1.         2.         0.10999993
 0.99000007 1.9900001  0.99000007 1.9900001  0.10999993 1.0099999
 2.0099998  1.         2.         0.09000007 1.         2.
 0.09000007 1.         2.         0.10999993]
step 10, loss: 0.1170337051153183
	params: [ 1.0930372   2.0984254   0.0677475   1.          2.          0.19703364
  0.88788944  1.887982    0.8915032   1.8949609   0.20725027  1.0765575
  2.0796342   1.0003536   2.          0.08717749  1.          2.
 -0.00253427  1.          2.          0.2032137 ]
step 20, loss: 0.10810360312461853
	params: [1.1308873  2.145422   0.07203323 1.         2.         0.2514174
 0.779795   1.7853216  0.79046917 1.8052882  0.30413726 1.0994068
 2.1037016  1.0002134  2.         0.13200857 1.         2.
 0.02946248 1.         2.         0.28788552]
step 30, loss: 0.10331025719642639
	params: [1.1680802  2.202446   0.06721077 1.         2.         0.2822615
 0.67114204 1.6919429  0.7

DeviceArray([2.0681665e+00, 4.8708310e+00, 6.9275476e-02, 1.0000000e+00,
             2.0000000e+00, 4.9883786e-01, 9.9998061e-04, 1.4649856e+00,
             2.1461281e-03, 1.6816711e+00, 7.4351692e-01, 1.1793922e+00,
             2.2085850e+00, 1.0027658e+00, 1.9999985e+00, 4.0449485e-02,
             1.0000000e+00, 2.0000000e+00, 4.9722541e-02, 1.0000000e+00,
             2.0000000e+00, 5.2111864e-01], dtype=float32)

In [12]:
from functools import partial

In [12]:
lb = np.zeros(params.shape)
ub = np.ones(params.shape)
dz = 0.1*np.ones(params.shape)

def penalty_fn (x,lb,dz):
    dept = (x-lb)/dz
    p = 1e3*jnp.power(dept,2)
    return(p)



@jax.jit #@partial(jax.jit,static_argnums=(1,2,3))
def penalty(params):

    mse = jnp.where(params < lb+dz, 1, 0) * jnp.power((params-lb)/dz,2)*1e3
    mse += jnp.where(params > ub-dz, 1, 0) * jnp.power((ub-params)/dz,2)*1e3
    
    return mse.sum()


In [13]:
params = jnp.array(list(c.get_ODEparameters().values()))
penalty(params)

DeviceArray(800000., dtype=float32)

In [33]:
jax.value_and_grad(penalty)(params)

(DeviceArray(806000., dtype=float32),
 DeviceArray([     0., 200000.,  20000.,      0., 200000.,  20000.,
                   0., 200000.,      0., 200000.,  20000.,      0.,
              200000.,      0., 200000.,  20000.,      0., 200000.,
               20000.,      0., 200000.,  20000.], dtype=float32))

In [7]:
lb = c.ODEparameters_lb.copy()
ub = c.ODEparameters_ub.copy()
dz = c.ODEparameters_dz.copy()

@jax.jit
def this_loss(params):
    mse = 0.0
    for i in range(len(params)):
        if params[i] <= lb[i]+dz[i]:
            dept = (params[i]-lb[i])/dz[i]
            penalty = 1e3*jnp.power(dept,2)
            mse += penalty
            
        elif params[i] > ub[i]-dz[i]:
            dept = (ub[i] - params[i])/dz[i]
            penalty = 1e3*jnp.power(dept,2)
            mse += penalty

    #params = jnp.clip(params, lb, ub)
    return mse

In [38]:
print(lb.shape)
print(ub.shape)
print(dz.shape)
print(params.shape)

(22,)
(22,)
(22,)
(22,)


In [39]:
loss_value, grads = jax.value_and_grad(this_loss)(params)

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function. 
While tracing the function this_loss at /var/folders/cx/9kyr3rt90c974wdygym_lhgh0000gn/T/ipykernel_97931/2333120683.py:5 for jit, this concrete value was not available in Python because it depends on the value of the argument 'params'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError

In [10]:
print(lb.shape)
print(ub.shape)
print(dz.shape)
print(params.shape)




(22,)
(22,)
(22,)
(22,)


DeviceArray([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0., 0., 0.], dtype=float32)